-- Drop everything and start fresh
-- Run this FIRST, then run SUPABASE_FULL_SCHEMA.sql

DROP TRIGGER IF EXISTS review_updated_timestamp ON reviews;
DROP FUNCTION IF EXISTS update_review_timestamp();

DROP TABLE IF EXISTS tracking_history CASCADE;
DROP TABLE IF EXISTS shipping_events CASCADE;
DROP TABLE IF EXISTS return_status_history CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS return_items CASCADE;
DROP TABLE IF EXISTS returns CASCADE;
DROP TABLE IF EXISTS banners CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS wishlist CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
